{
 "title": "Dashboard-WIP",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Verbrauch, Erzeugung und Batterie",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PV Gesamtleistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Gesamtleistung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AC Verbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Verbrauch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Leistung der Strings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PV String 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "String1_Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV String 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "String2_Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "aktuell erzeugte Leistung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Gesamtleistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie laden / entladen (minus)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Batterie",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "units": "watt",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Leistung und Autarkie (letzte 30 Tage)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Autarkie",
     "query": "SELECT 100*(1 - SUM(\"absbez\")/SUM(\"Verbrauch\")) FROM (SELECT ABS(\"Bezug\") AS \"absbez\", \"Verbrauch\" FROM \"AC\" ) WHERE $timeFilter GROUP BY time(1d) fill(null)"
    },
    {
     "alias": "Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "query": "SELECT sum(\"Gesamtleistung\")/(60*6*1000) FROM \"PV\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "Gesamtleistung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "aktueller Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Verbrauch" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "AC",
     "query": "SELECT abs(\"Bezug\") FROM \"AC\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Bezug" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "AC",
     "query": "SELECT abs(last(\"Bezug\")) FROM \"AC\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Bezug" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}